### PR TITLE
Test Reviews

### PR DESCRIPTION
**Pull request by QcTL**

### CODE REVIEW

**Review by AniolMG — COMMENTED** [review]
Indiferente

**Review by AniolMG — APPROVED** [review]
Yes I like

**Review by PauJimeno — APPROVED** [review]
mol malamen sanyo jordi

**Review by AniolMG — CHANGES_REQUESTED** [review]
I don't like
Change pls

**Review by AniolMG — APPROVED** [review]
Yes now it good very thanks

**Review by PauJimeno — APPROVED** [review]
meparese bien 👍

**Review by AniolMG — CHANGES_REQUESTED** [review]
No actualy bad stopid

**Review by AniolMG — DISMISSED** [review]

**Review by AniolMG — CHANGES_REQUESTED** [review]
you dump changeit

**Review by AniolMG — CHANGES_REQUESTED** [review]
no this is bad vey stopids

**Review by PauJimeno — CHANGES_REQUESTED** [review]
mol malamen sta mal >:c

**Comment by QcTL** [comment]
NOOO

**Review by AniolMG — CHANGES_REQUESTED** [review]
NOOOOOOOOOOOOOOOOOO ZA WARUDO TOKI WO TOMARE

**Comment by AniolMG** [comment]
NO.

**Comment by AniolMG** [comment]
sorry for necro

**Pull request merged**
